package com.coderhouse.models;
import com.coderhouse.repositories.OrdersRepository;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
@Schema(description = "Orders Model")
@Entity
@Table(name="Orders")
public class Orders {
    @Schema(description = "Order Id", requiredMode = Schema.RequiredMode.NOT_REQUIRED, example = "AutoGeneratedValue")
    @Id
    @SequenceGenerator(
            name = "ticket_sequence",
            sequenceName = "ticket_sequence",
            allocationSize = 1
    )
    @GeneratedValue(
            generator = "ticket_sequence",
            strategy = GenerationType.SEQUENCE
    )
    private Long orderId;
    @Schema(description = "Customers link")
    @ManyToOne
    @JoinColumn(name = "dni")
    private Customers customer;
    @Schema(description = "Orders Link")
    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    @JsonManagedReference
    private List<OrderProduct> orderProducts = new ArrayList<>();
    @Schema(description = "Order date", requiredMode = Schema.RequiredMode.REQUIRED, example = "06-05-2024")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy")
    private Date saleDate;
    @Schema(description = "Order Id", requiredMode = Schema.RequiredMode.NOT_REQUIRED, example = "AutoGeneratedValue")
    private double totalAmount;

    public Orders() {
        super();
    }

    @Override
    public String toString() {
        return "Orders{" +
                "orderId=" + orderId +
                ", customer=" + customer +
                ", orderProducts=" + orderProducts +
                ", saleDate=" + saleDate +
                ", totalAmount=" + totalAmount +
                '}';
    }

    public Long getOrderId() {
        return orderId;
    }

    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    public Date getSaleDate() {
        return saleDate;
    }

    public void setSaleDate(Date saleDate) {
        this.saleDate = saleDate;
    }

    public double getTotalAmount() {
        return totalAmount;
    }

    public void setTotalAmount(double totalAmount) {
        this.totalAmount = totalAmount;
    }

    public Customers getCustomer() {
        return customer;
    }

    public void setCustomer(Customers customer) {
        this.customer = customer;
    }

    public List<OrderProduct> getOrderItems() {
        return orderProducts;
    }

    public void setOrderItems(List<OrderProduct> orderProducts) {
        this.orderProducts = orderProducts;
    }
}
